name: sanyan_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  audioplayers: ^6.1.0
  record: ^5.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  google_fonts: ^6.2.1

  # Foundation packages
  sanyan_common_ui:
    path: foundation_packages/sanyan_common_ui
  sanyan_routes:
    path: foundation_packages/sanyan_routes
  sanyan_network:
    path: foundation_packages/sanyan_network
  sanyan_user:
    path: foundation_packages/sanyan_user

  # Business packages
  sanyan_auth:
    path: business_packages/sanyan_auth
  sanyan_chat:
    path: business_packages/sanyan_chat
  sanyan_contacts:
    path: business_packages/sanyan_contacts
  sanyan_settings:
    path: business_packages/sanyan_settings
  sanyan_status:
    path: business_packages/sanyan_status

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.3
  mockito: ^5.4.4
  build_runner: ^2.4.9
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - fonts/
